# This is a basic workflow to help you get started with Actions

name: Validate Json

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run validator
        shell: pwsh
        run: Test-Json values.json
